### ISSUE TITLE
Minor issue HttpClientModule import

### ISSUE THREAD

**Issue by lexcaraig** [kmathy/ngx-reduxor#3]
`import { HttpClientModule } from '@angular/common/http';`

missing upon generating store. :)

**Comment by kmathy** [comment]
Oups, didn't see it because I'm using an APIService outside my store 🙈 
I will patch with this fix!

Thanks!

**Comment by kmathy** [comment]
Fixed. You can update to 1.0.1

**Comment by lexcaraig** [comment]
Thanks for this. I kinda wanna help improve this generator. It’s awesome. I hope i know how to contribute. Haha.

**Comment by kmathy** [comment]
In the section 'Project' of the repository, I added in To Do that I will write a documentation to contribute to the source code and how we can improve it. Thanks for your help! :)

**Comment by lexcaraig** [comment]
Well, as of the moment i have plenty of time that’s why i want to contribute. But thanks a lot! This project really help me a lot on setting up my project. :)
