### ISSUE TITLE
V1.1.0

### ISSUE THREAD

**Issue by kmathy** [kmathy/ngx-reduxor#8]
- [x] Config file
- [ ] more structured app
- [x] storeDev-Tool

Used for Zenhub

**Comment by kmathy** [comment]
Refactoring done, separating files to easily scale the tool.

@lexcaraig Don't hesitate to pull the latest commit, you'll probably be glad to work on it :)

**Comment by lexcaraig** [comment]
Yeah. Alright. Thanks!
